sudo: false
language: node_js
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - /^v\d+\.\d+\.\d+.*$/
notifications:
  email: false
before_script:
  - npm run build
# script:
#   - npm run test
# before_install:
#   - npm i -g npm@6.4.1
node_js:
  - "node"
deploy:
  provider: npm
  email: "${NPM_EMAIL}"
  api_key: "${NPM_AUTH_TOKEN}"
  skip_cleanup: true
  on:
    condition: '"x${NPM_AUTH_TOKEN}" != "x" && "x${NPM_EMAIL}" != "x"'
    tags: true